server:
  port: 8080

spring:
  application:
    name: account-auth-service
  webflux:
    base-path: /account-auth-service
management:
  otlp:
    tracing:
      endpoint: http://192.168.7.100:24318/v1/traces
  tracing:
    baggage:
      correlation:
        fields:
          - correlationId
      remote-fields:
        - correlationId
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}|1|%level|${spring.application.name:-}|%X{traceId},%X{spanId},%X{correlationId}|${PID:-}|%thread|%logger{100}|%message%n"
